# A list of entities that can be caught with the Mob Catcher
# Regardless of this configuration, only mob entities can be caught.
# Refer to this page for a list of possible entity types: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
entity_whitelist:
  - ALLAY
  - ARMADILLO
  - AXOLOTL
  - BAT
  - BEE
  - BLAZE
  - BOGGED
  - BREEZE
  - CAMEL
  - CAT
  - CAVE_SPIDER
  - CHICKEN
  - COD
  - COW
  - CREAKING
  - CREEPER
  - DOLPHIN
  - DONKEY
  - DROWNED
  - ENDERMAN
  - ENDERMITE
  - EVOKER
  - FOX
  - FROG
  - GHAST
  - GLOW_SQUID
  - GOAT
  - GUARDIAN
  - HAPPY_GHAST
  - HOGLIN
  - HORSE
  - HUSK
  - ILLUSIONER
  - IRON_GOLEM
  - LLAMA
  - MAGMA_CUBE
  - MOOSHROOM
  - MULE
  - OCELOT
  - PANDA
  - PARROT
  - PHANTOM
  - PIG
  - PIGLIN
  - PIGLIN_BRUTE
  - PILLAGER
  - POLAR_BEAR
  - PUFFERFISH
  - RABBIT
  - RAVAGER
  - SALMON
  - SHEEP
  - SHULKER
  - SILVERFISH
  - SKELETON
  - SKELETON_HORSE
  - SLIME
  - SNIFFER
  - SNOW_GOLEM
  - SPIDER
  - SQUID
  - STRAY
  - STRIDER
  - TADPOLE
  - TRADER_LLAMA
  - TROPICAL_FISH
  - TURTLE
  - VEX
  - VILLAGER
  - VINDICATOR
  - WANDERING_TRADER
  - WITCH
  - WITHER_SKELETON
  - WOLF
  - ZOGLIN
  - ZOMBIE
  - ZOMBIE_HORSE
  - ZOMBIE_VILLAGER
  - ZOMBIFIED_PIGLIN