name: Build Addons

on:
  push:
    branches:
      - '**'
  release:
    types: [ created ]

jobs:
  build-jetpacks:
    name: Build Jetpacks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            jetpacks:addonJar
            -PoutDir=../artifacts/

      - name: Upload Artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: Jetpacks
          path: artifacts/
  
  build-logistics:
    name: Build Logistics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            logistics:addonJar
            -PoutDir=../artifacts/

      - name: Upload Artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: Logistics
          path: artifacts/
  
  build-machines:
    name: Build Machines
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            machines:addonJar
            -PoutDir=../artifacts/

      - name: Upload Artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: Machines
          path: artifacts/
  
  build-simple-upgrades:
    name: Build Simple-Upgrades
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            simple-upgrades:addonJar
            -PoutDir=../artifacts/

      - name: Upload Artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: Simple-Upgrades
          path: artifacts/
  
  build-vanilla-hammers:
    name: Build Vanilla-Hammers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            vanilla-hammers:addonJar
            -PoutDir=../artifacts/

      - name: Upload Artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: Vanilla-Hammers
          path: artifacts/
